name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: AlasDiablo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          mvn --settings settings.xml deploy
